### PR TITLE
new: EKS Pod Identity lab

### LINKED ISSUE #764: EKS Pod Identity lab
### Outline the high level topic of the lab

https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/

### Provide the flow of the lab exercise, including what sample application components will be used

This lab can use the same basic flow as the IRSA lab.

### What additional AWS infrastructure or EKS addons/components will need to be created or installed to support this lab?

Pod identity addon

### What additional software or configuration will be required in the Cloud9 IDE?

None

### Are enhancements to the retail sample application required to support this lab exercise?

Yes, the SDKs for the sample application will need to be updated for pod identity support.

### PR DESCRIPTION
**Pull request by ashoksrirama**
#### Which issue(s) this PR fixes:

Fixes #764

#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by niallthomson** [comment]
To align with our intent in #714 lets install the pod identity addon using the CLI instead of Terraform. You can see an example of where we've done this in the EBS lab https://www.eksworkshop.com/docs/fundamentals/storage/ebs/ebs-csi-driver

**Comment by ashoksrirama** [comment]
> To align with our intent in #714 lets install the pod identity addon using the CLI instead of Terraform. You can see an example of where we've done this in the EBS lab https://www.eksworkshop.com/docs/fundamentals/storage/ebs/ebs-csi-driver

Fixed

**Comment by niallthomson** [comment]
Looks good to me. @rodrigobersa let us if you're good for this to merge.

**Review by rodrigobersa — APPROVED** [review]
Ready @niallthomson !

**Comment by niallthomson** [comment]
Thanks everyone!

**Pull request merged**
