### PR TITLE
new: Deploy and monitor ML models with GPUs on Amazon EKS

### PR DESCRIPTION
**Pull request by shivkumr**
#### What this PR does / why we need it:
This is a new lab to deploy and monitor ML model on Amazon EKS

#### Which issue(s) this PR fixes:
First PR for this new lab

Fixes # NA

#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)

  EKS Workshop
    AI/ML on EKS
      Deploy and Monitor GenAI Model on EKS
        ✔ Deploy and Monitor GenAI Model on EKS (1342913ms)
        ✔ Install Karpenter and KubeRay Operator (211251ms)
        ✔ Install Jupyterhub (444619ms)
        ✔ Model Training (60899ms)
        ✔ Model Inference (312600ms)
        ✔ Monitor GPU Workloads on EKS (4945ms)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bkgardiner** [comment]
Karpenter should be preinstalled in this lab as it doesn't really add much to the lab. Take a look at the Inference with AWS Inferentia lab (https://www.eksworkshop.com/docs/aiml/inferentia/). This lab comes with Karpenter preinstalled. 

In the Jupyter Notebook commands section it would be nice to get some explanation on what this code is exactly doing. This would also enable to user to read through the explanation while waiting for the code to be executed. 

Other than that this lab looks really good! Thank you for creating it.

**Review by bkgardiner — APPROVED** [review]
This looks good to me.

**Comment by svennam92** [comment]
Awesome! Some comments:
1) The prepare-environment block should have a link out to the Terraform like in other modules
2) Please explain hardware infrastructure being used. Can we outline the Karpenter nodepools that are created for the user? Explain what g5 instances are and why we need them for the lab. Example: https://eksworkshop.com/docs/aiml/chatbot/nodepool
3) The titles are for the AI/ML modules are not distinct enough. How about something like "Training StableDiffusion on NVIDIA GPUs". The inference piece is implied when we're doing training.

**Review by svennam92 — CHANGES_REQUESTED** [review]
Awesome! Some comments:

1. The prepare-environment block should have a link out to the Terraform like in other modules
1. Please explain hardware infrastructure being used. Can we outline the Karpenter nodepools that are created for the user? Explain what g5 instances are and why we need them for the lab. Example: https://eksworkshop.com/docs/aiml/chatbot/nodepool
1. The titles are for the AI/ML modules are not distinct enough. How about something like "Training StableDiffusion on NVIDIA GPUs". The inference piece is implied when we're doing training.

**Pull request closed without merging**
