### PR TITLE
chore: Fixed cleanup of control plane logging lab

### LINKED ISSUE #696: [Bug]: The cleanup of observability can lead to broken environment since the cleanup script can fails to disable the logs
### Installation method

Workshop Studio

### What happened?

When my customer tried to run command shared in [workshop documentation](https://www.eksworkshop.com/docs/autoscaling/compute/cluster-autoscaler/):
`prepare-environment autoscaling/compute/cluster-autoscaler`

They received CLI response:
```
Refreshing copy of workshop repository from GitHub...

Resetting the environment, please wait
Disabling EKS control plane logs...

An error occurred (InvalidParameterException) when calling the UpdateClusterConfig operation: No changes needed for the logging config provided
```

### What did you expect to happen?

No error messages, and a successful installation of Kubernetes Cluster Autoscaler in the Amazon EKS cluster

### How can we reproduce it?

Try following the [Cluster Autoscaler part of the workshop ](https://www.eksworkshop.com/docs/autoscaling/compute/cluster-autoscaler/)after completing the workshop prerequisites 

### Anything else we need to know?

In order to fix, customer also followed [Navigating the labs](https://www.eksworkshop.com/docs/introduction/navigating-labs/) documentation and ran `prepare-environment` command but this didn't fix the issue.

Root cause of error could be [TF module](https://github.com/aws-samples/eks-workshop-v2/blob/stable/manifests/modules/autoscaling/compute/cluster-autoscaler/.workshop/terraform/addon.tf) making a call to [v4.25 of this GitHub repo](http://github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.25.0//modules/kubernetes-addons/cluster-autoscaler). That repo had been updated to v5 and things had moved around. v4 to v5 migration documentation is still in progress but I found [this guide](https://aws-ia.github.io/terraform-aws-eks-blueprints/v4-to-v5/addons/) which recommends to apply below changes to the code:

- change source to “aws-ia/eks-blueprints-addons/aws”
- add a new line: version = "~> 1.0"

### EKS version

Not sure - probably the default value in EKS Workshop Cloudfromation. It could be 1.25 as stated in [documentation page](https://www.eksworkshop.com/docs/introduction/setup/your-account/using-eksctl)

### PR DESCRIPTION
**Pull request by ROunofF**
#### Which issue(s) this PR fixes:

Fixes #696 

#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test module="observability"` and it was successful

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by niallthomson** [comment]
I think the logging logic probably needs to be more complex than this. If we want to be able to implement something that tells the user when a command failed and which log file there will need to be something that catches the error since `set -e` will exit. Also, it looks like this is redirecting stdout as well is that correct?

**Comment by ROunofF** [comment]
> Also, it looks like this is redirecting stdout as well is that correct?

This will capture (in the log) **and** display both stdout and stderr. Since we have set -e, in the observability I added the || true since we know the error is possible.

**Comment by niallthomson** [comment]
Oh yeah, forgot its tee.

What I mean by the logic is that in the script that curls reset-environment, runs and it and uses tee ideally we would catch any error that happens in the reset-environment run and message the user to refer to appropriate log file by exact path.

For example

```
$ prepare-environment mymodule
[...]
An error occurred, please contact your workshop proctor or raise an issue at https://github.com/aws-samples/eks-workshop-v2/issues
Log file can be found at /eks-workshop/logs/action[...].log
```

**Comment by ROunofF** [comment]
> Oh yeah, forgot its tee.
> 
> What I mean by the logic is that in the script that curls reset-environment, runs and it and uses tee ideally we would catch any error that happens in the reset-environment run and message the user to refer to appropriate log file by exact path.
> 
> For example
> 
> ```
> $ prepare-environment mymodule
> [...]
> An error occurred, please contact your workshop proctor or raise an issue at https://github.com/aws-samples/eks-workshop-v2/issues
> Log file can be found at /eks-workshop/logs/action[...].log
> ```

Have a log at the latest PR, this should be pretty similar to your suggestions

**Comment by tceren** [comment]
hi team, what are we missing to continue merging this pull request? happy to help!

**Comment by niallthomson** [comment]
I've removed the logging feature from this PR for now so we can get the basic fix merged.

**Pull request merged**
