### PR TITLE
update: Changes to EKS cluster logging instructions

### PR DESCRIPTION
**Pull request by kathanjit**
#### What this PR does / why we need it:
This fixes the issue 978. Changing the content for observability to point to console. 
Updating with the latest console screens
#### Which issue(s) this PR fixes:

Fixes # https://github.com/aws-samples/eks-workshop-v2/issues/978

#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test module="<module>"` it was successful (see https://github.com/aws-samples/eks-workshop-v2/blob/main/docs/automated_tests.md)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by niallthomson** [comment]
I'm having difficulty breaking down exactly what this is changing due to the fact its images. Can you describe the changes you made?

**Comment by kathanjit** [comment]
The document file was missed. Changes made are on the screen shot. Updated the screens to point to how to enable control pane logging through console

**Comment by jsgoudar** [comment]
> I'm having difficulty breaking down exactly what this is changing due to the fact its images. Can you describe the changes you made?

The changes are to show the user that about observability tooling and highlight the ability to enable control plane logs without code and using console. We retained the use of Api as well.

**Comment by jsgoudar** [comment]
Reviewed, changes look good, but branch is out-of-date, please merge

**Comment by kathanjit** [comment]
Took the latest from master. Branch should be up to date

**Comment by jsgoudar** [comment]
Approved, looks good to me.

**Pull request merged**
