### PR TITLE
Adding scenario with Amazon FSxN for NetApp ONTAP (for shared PVC)

### PR DESCRIPTION
**Pull request by mickeysh**
#### What this PR does / why we need it:

- Add FSxN for NetApp ONTAP installation and CSI driver installation in the terraform (using the general Helm EKS add-on.
- Add scenarios to configure the FSxN CSI driver and create a shared PVC based on the assets application. This is due to field and customer ask to have code samples and samples scenario to integrate EKS with FSxN (specifically that it's missing in EKS workshop).
- #### Which issue(s) this PR fixes:

Fixes #

#### Quality checks

- [ ] My content adheres to the style guidelines
- [ ] I ran `make test` or `make e2e-test` and it was successful

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by svennam92** [comment]
@mickeysh can you rebase this to the latest commit to catch the netlify build changes?

**Comment by mickeysh** [comment]
@svennam92 Should be fine now. Do you need me to open a new PR or keep this one?

**Comment by mickeysh** [comment]
@svennam92 Looks good 💯 What are the plans for merging this. When do you plan to add the more advanced storage options (other than EBS/EFS) category?

**Comment by mickeysh** [comment]
> It's working now, you can see the preview in the Netlify build above: https://deploy-preview-383--eks-workshop.netlify.app/docs/fundamentals/storage/fsx%20for%20netapp%20ontap/

It looks like it's failing while trying to push to my repo on step `Helm Chart Update`
```
 /usr/bin/git push --force-with-lease origin HEAD:refs/heads/update-helm-charts
  remote: Permission to mickeysh/eks-workshop-v2.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/mickeysh/eks-workshop-v2/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by mickeysh** [comment]
> Now confirm the new product image newproduct.png

**Comment by svennam92** [comment]
@mickeysh I re-opened the PR, looks like it was closed by accident.

**Comment by mickeysh** [comment]
@heinrichse I've updated the section you mentioned and it should workshop and you should see the new file only on the first pod and not the second. 

@svennam92 What is the status of the review on this item?

**Comment by heinrichse** [comment]
> @heinrichse I've updated the section you mentioned and it should workshop and you should see the new file only on the first pod and not the second.
> 
> @svennam92 What is the status of the review on this item?

We have recently elected a maintainer for the Storage Module of the Workshop who will be assisting in reviewing this PR. Thanks for your patience as we get this new Module rolled out!

**Review by pengc99 — COMMENTED** [review]
Looks good to me, checked this in the preview and it looks like the updates to update only the pod and not the cluster (similar to https://github.com/aws-samples/eks-workshop-v2/pull/526) are in.

**Comment by mickeysh** [comment]
> Looks good to me, checked this in the preview and it looks like the updates to update only the pod and not the cluster (similar to #526) are in.

@pengc99 thanks for the review. Is anything is missing to get this module rolled out?

**Comment by pengc99** [comment]
> > Looks good to me, checked this in the preview and it looks like the updates to update only the pod and not the cluster (similar to #526) are in.
> 
> @pengc99 thanks for the review. Is anything is missing to get this module rolled out?

I need to verify this in my local environment and then I will talk to the maintainers about getting it added!

**Comment by pengc99** [comment]
I've checked and verified the content on this PR again and I'll talk to the maintainers to get it merged. There are a few issues that we noticed while testing this PR, some of which are related to the older codebase that was used in the PR and would get resolved with a rebase:

1. Versioning issue from [issue 538](https://github.com/aws-samples/eks-workshop-v2/issues/538) still exists - would be solved with a rebase
2. RDS versioning issue from [issue 498](https://github.com/aws-samples/eks-workshop-v2/issues/498) still exists - would be solved with a rebase
3. During testing, we noticed sometimes the modules weren't getting pulled into /workspace/modules/fundamentals/storage/fsxn - once the modules were copied over manually the code and workshop instructions worked
4. During testing, we also noticed some weird issues with the credentials or IP addresses not getting set correctly in /workspace/modules/fundamentals/storage/fsxn/fsxn-secret.yaml - we would have to update the username to be vsadmin and resync the password in the AWS console before the Kustomization could be applied. 
5. Using variables in the Kustomization (in this case, the $FSXN_IP variable in /workspace/modules/fundamentals/storage/fsxn/fsxn-backend-nas.yaml) spits out a warning that using an environment variable is deprecated and will be eliminated soon:
``WARNING: This Kustomization is relying on a bug that loads values from the environment when they are omitted from an env file. This behaviour will be removed in the next major release of Kustomize.``

**Review by heinrichse — APPROVED** [review]
Reviewed. Proceeding with merging into the main branch. Additional issues will be addressed with new PRs after merging.

**Comment by mickeysh** [comment]
@svennam92 I see the change was merged, and I can see all changes in the main, but on the website the left panel update is missing (The update to the index pages are present)

**Comment by niallthomson** [comment]
Hey @mickeysh, we were scheduled to publish the restructure of the workshop infrastructure we've been working on last Friday and there was not time to properly migrate this module entirely without blocking that effort. The module content has been moved to the correct place in the repository but temporarily disabled. I will be working to migrate this to the new structure towards the end of this week and then it will be visible.

Sorry for the confusion.

**Comment by mickeysh** [comment]
@niallthomson Just wanted to know there aren't any issue :) 
Thank you. 
BTW where in the workshop would be the best place to publish more advanced labs for storage like data protection, cross region replication etc.?

**Pull request merged**
