### PR TITLE
fix command used to scale the nodegroup

### PR DESCRIPTION
**Pull request by yash555kumar**
#### What this PR does / why we need it:
Fix command for scaling nodegroup
#### Which issue(s) this PR fixes:
While description says we are increasing the minimum node count to `4`, command still has `--node-min` as `3`

Fixes #
 - Change command used in the documentation
 
#### Quality checks

- [x] My content adheres to the style guidelines
- [x] I ran `make test` or `make e2e-test` and it was successful

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ROunofF — DISMISSED** [review]
Consistency with the text.

**Comment by niallthomson** [comment]
This was done in purpose. We're scaling the nodes to 4 but leaving the minimum as 4 is fine. If anything it illustrates that you can adjust the desired count while leaving the lower and upper bounds static.

Do we need to call that out?

**Comment by yash555kumar** [comment]
I got confused by it after reading the statement above. I feel this is required to be consistent with the statement above.

**Comment by niallthomson** [comment]
Can you update the PR to change the wording so that it only mentions desired size? I will merge that.

**Comment by yash555kumar** [comment]
@niallthomson updated wording to match the command. Could you please review.

**Comment by niallthomson** [comment]
Looks good, thanks!

**Pull request merged**
